language: node_js
node_js:
- '7'

before_script:
  - npm run build

test:
  - 'npm run lint'

after_success:
  - 'sh ./bin/travis-deploy.sh gh-pages 7'

env:
global:
    - GIT_USER: Travis CI
    - GIT_EMAIL: kamataryo@users.noreply.github.com
    - GH_REF: github.com/kamataryo/demo.git
